global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'demo-app'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['demo_service_v1:2112']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']